In [1]:
# 导入弹性网
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
import pandas as pd
import copy
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

# # 用于构造交互项的列
column_interaction = ['Leq_mean', 'Leq_std', 'Loudness_mean', 'Loudness_std', 'Roughness_mean', 'Roughness_std',
                      'Sharpness_mean', 'Sharpness_std', 'Fluct_mean', 'Fluct_std', 'Tonality_mean', 'Tonality_std']

# 转化为小写
for i in range(len(column_interaction)):
    column_interaction[i] = column_interaction[i].lower()

# 增加了排序列
column_interaction_order = copy.deepcopy(column_interaction)
column_interaction_order.insert(0, 'order')

# 读入数据
path = r'.\input\feature_83.csv'
data_83 = pd.read_csv(path)
# 所有列
columns = data_83.columns
y_column = columns[-1]

data_x = data_83[column_interaction_order]
data_y = data_83[y_column]
data_x, data_y

(    order  leq_mean  leq_std  loudness_mean  loudness_std  roughness_mean  \
 0       1  64.66645  1.56539       17.75490       1.86917         2.17955   
 1       2  64.46865  2.12706       15.93369       2.01787         2.34253   
 2       3  62.65053  2.71845       14.61514       2.42780         2.02092   
 3       4  64.14055  2.67668       14.42197       2.36871         1.80561   
 4       5  64.21175  2.65563       16.29315       3.11429         2.25994   
 ..    ...       ...      ...            ...           ...             ...   
 78     79  63.60349  0.54465       14.84529       0.83521         2.06608   
 79     80  62.72917  4.30253       14.62678       4.56900         2.74957   
 80     81  63.67776  3.05028       14.71222       2.29281         2.10886   
 81     82  63.29483  2.21022       13.90514       2.09026         2.02066   
 82     83  63.90276  1.58277       16.14553       1.19750         2.11045   
 
     roughness_std  sharpness_mean  sharpness_std  fluct_mean 

In [2]:
# 打乱数据,训练测试9:1
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=.05, random_state=0)
x_train_array = x_train.values
x_test_array = x_test.values
x_train_array

array([[3.900000e+01, 6.388686e+01, 1.340000e+00, ..., 2.643000e-02,
        1.641000e-02, 2.153000e-02],
       [3.000000e+00, 6.265053e+01, 2.718450e+00, ..., 3.142000e-02,
        3.378000e-02, 2.960000e-02],
       [5.600000e+01, 6.430822e+01, 2.615110e+00, ..., 2.283000e-02,
        3.827000e-02, 3.506000e-02],
       ...,
       [6.500000e+01, 6.491698e+01, 8.952200e-01, ..., 1.990000e-02,
        2.435300e-01, 5.971000e-02],
       [4.800000e+01, 6.303810e+01, 1.120860e+00, ..., 2.132000e-02,
        2.687000e-02, 2.607000e-02],
       [4.500000e+01, 6.162466e+01, 5.737750e+00, ..., 1.056400e-01,
        6.689000e-02, 3.958000e-02]])

In [3]:
poly = PolynomialFeatures(degree=3)
x_train_array = poly.fit_transform(x_train_array)
x_test_array = poly.fit_transform(x_test_array)
y_train_array = y_train.values
y_test_array = y_test.values

In [4]:
# 训练 ElasticNet
alpha = 0.1
enet = ElasticNet(alpha=alpha, l1_ratio=0.1, normalize=True)
# enet = make_pipeline(StandardScaler(), ElasticNet())
enet.fit(x_train_array, y_train_array)

# 验证
predict = enet.predict(x_test_array)
enet.score(x_train_array, y_train_array), enet.score(x_test_array, y_test_array)
predict, y_test_array

E:\Python\Anaconda\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), ElasticNet())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to original_alpha * np.sqrt(n_samples) if l1_ratio is 1, and to original_alpha * n_samples if l1_ratio is 0. For other values of l1_ratio, no analytic formula is available.
  warnings.warn(


(array([5.12536382, 5.11980908, 5.05091927, 4.49012834, 5.34128505]),
 array([5.4959 , 4.93033, 3.7623 , 3.7541 , 5.28279]))