In [13]:
from numpy import random
import numpy as np
import pandas as pd

# 不用dataframe，只用ndarray
# 计算速度：ndarray > Series > list > DataFrame

pd.reset_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
feature = pd.read_excel(r'./input/feature.xls')
col = feature.columns[10:-1]
feature_use = feature[col]

# 转化为ndarray
feature_use = feature_use.to_numpy()

In [14]:
# 聚类取平均值，用于计算更新聚类点
def cluster_mean(cluster):
    return np.mean(cluster, axis=0)


# 计算两点的欧氏距离
def Euclidean_distance(x, y):
    distance = np.sqrt(np.sum((x - y) ** 2))
    return distance

In [15]:
# 对数据进行正态——标准化
def feature_normalize(dataset):
    mu = np.mean(dataset, axis=0)
    sigma = np.std(dataset, axis=0)
    return (dataset - mu) / sigma

In [16]:
feature_use = feature_normalize(feature_use)
mean_points = cluster_mean(feature_use)
m = feature_use.shape[0]
points_distance_to_center = np.zeros(feature_use.shape[0])

for i in range(m):
    temp_dist = Euclidean_distance(feature_use[i], mean_points)
    points_distance_to_center[i] = temp_dist

points_distance_to_center = pd.DataFrame(points_distance_to_center)
name_list = feature[feature.columns[1]]
name_list = pd.DataFrame(name_list.values)
points_distance_to_center = pd.concat([name_list, points_distance_to_center], axis=1)

points_distance_to_center.to_csv(r"./output/points_distance_to_center.csv")

In [19]:
points_distance_to_center = points_distance_to_center.values
outlier_index = []

for i in range(len(points_distance_to_center)):
    if points_distance_to_center[i, 1] > 25:
        outlier_index.append(i)

np.matrix(outlier_index)

matrix([[  14,   16,   17,  114,  115,  137,  165,  187,  354,  653,
         1577, 2427, 2428, 2434, 2436, 2772, 2793, 2841, 2978, 3108,
         3848, 3849, 3850, 3851, 3852, 3854, 3855, 3856, 3857, 3858,
         3859, 3878, 4071, 4073, 4074, 4075, 4076, 4080, 4501, 4551,
         4717, 5217, 5221, 5223, 5224, 5304, 5311, 5312, 5313, 5692,
         5694, 5695, 5696, 5699, 6598]])

In [17]:
a = np.ones((3, 4))
a[1,1] = 10
a[2,2] = 100
a[0,0] = 5

print(a)
mu = np.mean(a,axis=0)
s = np.std(a,axis=0)
print(np.mean(a,axis=0))
print(np.std(a,axis=0))
print((a - mu)/s)

[[  5.   1.   1.   1.]
 [  1.  10.   1.   1.]
 [  1.   1. 100.   1.]]
[ 2.33333333  4.         34.          1.        ]
[ 1.88561808  4.24264069 46.66904756  0.        ]
[[ 1.41421356 -0.70710678 -0.70710678         nan]
 [-0.70710678  1.41421356 -0.70710678         nan]
 [-0.70710678 -0.70710678  1.41421356         nan]]


C:\Users\Black\AppData\Local\Temp\ipykernel_67548\3303024914.py:11: RuntimeWarning: invalid value encountered in true_divide
  print((a - mu)/s)


In [1]:
xtr_col4 = ['Leq_mean', 'Leq_std', 'Leq_25', 'Leq_median',
            'Leq_75', 'Leq_10-Leq_90', 'Loudness_mean', 'Loudness_std',
            'Loudness_25', 'Loudness_median', 'Loudness_75',
            'Loudness_10-Loudness_90', 'Roughness_mean', 'Roughness_std',
            'Roughness_25', 'Roughness_median', 'Roughness_75',
            'Roughness_10-Roughness_90', 'Sharpness_mean', 'Sharpness_std',
            'Sharpness_25', 'Sharpness_median', 'Sharpness_75',
            'Sharpness_10-Sharpness_90', 'Fluct_mean', 'Fluct_std', 'Fluct_25',
            'Fluct_median', 'Fluct_75', 'Fluct_10-Fluct_90', 'Tonality_mean',
            'Tonality_std', 'Tonality_25', 'Tonality_median', 'Tonality_75',
            'Tonality_10-Tonality_90', 'leq_w', 'leq_esm', 'sharpness_slop2', 'tonality_esm',
            'tonality_phimax', 'crz']

In [3]:
len(xtr_col4)

42