In [18]:
import pandas as pd
import numpy as np

data_44_path = r'.\input\score_44.csv'
data_44 = pd.read_csv(data_44_path)
use_col = ['声音类别', '吵闹度']
data_44_use = data_44[use_col]
data_44_use

声音类别  吵闹度
0        42    4
1        43    5
2        20    5
3        38    4
4        14    3
...     ...  ...
14416    13    5
14417     9    6
14418    20    8
14419    10    5
14420    12    6

[14421 rows x 2 columns]

In [19]:
# dataframe -> array np.array(df)
# array -> dataframe pd.dataframe(array)
data_44_array = np.array(data_44_use)
data_44_array

array([[42,  4],
       [43,  5],
       [20,  5],
       ...,
       [20,  8],
       [10,  5],
       [12,  6]], dtype=int64)

In [20]:
noise_mean_score = np.zeros((44, 2))
noise_mean_score

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
for i in range(1, 45):
    score_sum = 0
    people_num = 0
    for j in range(len(data_44_array)):
        if data_44_array[j, 0] == i:
            score_sum += data_44_array[j, 1]
            people_num += 1

    mean_score = score_sum / people_num
    noise_mean_score[i - 1, 0] = int(i)
    noise_mean_score[i - 1, 1] = mean_score

noise_mean_score

array([[ 1.        ,  5.75987842],
       [ 2.        ,  5.65957447],
       [ 3.        ,  6.56534954],
       [ 4.        ,  5.7993921 ],
       [ 5.        ,  6.07033639],
       [ 6.        ,  6.03658537],
       [ 7.        ,  4.52777778],
       [ 8.        ,  5.81230769],
       [ 9.        ,  5.27134146],
       [10.        ,  3.96024465],
       [11.        ,  5.45288754],
       [12.        ,  4.97230769],
       [13.        ,  3.77675841],
       [14.        ,  3.82874618],
       [15.        ,  4.96923077],
       [16.        ,  3.37386018],
       [17.        ,  4.27217125],
       [18.        ,  4.52134146],
       [19.        ,  4.59270517],
       [20.        ,  4.11419753],
       [21.        ,  3.3768997 ],
       [22.        ,  4.63190184],
       [23.        ,  4.3768997 ],
       [24.        ,  4.00911854],
       [25.        ,  5.20183486],
       [26.        ,  4.36170213],
       [27.        ,  4.57186544],
       [28.        ,  4.61398176],
       [29.        ,

In [22]:
noise_mean_score = pd.DataFrame(noise_mean_score)
noise_mean_score

0         1
0    1.0  5.759878
1    2.0  5.659574
2    3.0  6.565350
3    4.0  5.799392
4    5.0  6.070336
5    6.0  6.036585
6    7.0  4.527778
7    8.0  5.812308
8    9.0  5.271341
9   10.0  3.960245
10  11.0  5.452888
11  12.0  4.972308
12  13.0  3.776758
13  14.0  3.828746
14  15.0  4.969231
15  16.0  3.373860
16  17.0  4.272171
17  18.0  4.521341
18  19.0  4.592705
19  20.0  4.114198
20  21.0  3.376900
21  22.0  4.631902
22  23.0  4.376900
23  24.0  4.009119
24  25.0  5.201835
25  26.0  4.361702
26  27.0  4.571865
27  28.0  4.613982
28  29.0  4.390244
29  30.0  2.609091
30  31.0  4.288754
31  32.0  3.905199
32  33.0  3.907692
33  34.0  4.387195
34  35.0  3.710366
35  36.0  3.848024
36  37.0  2.764526
37  38.0  4.127660
38  39.0  4.871166
39  40.0  3.993921
40  41.0  5.206687
41  42.0  2.541033
42  43.0  4.097561
43  44.0  3.054545

In [23]:
noise_mean_score.columns = ['category', 'noise_score']
noise_mean_score

category  noise_score
0        1.0     5.759878
1        2.0     5.659574
2        3.0     6.565350
3        4.0     5.799392
4        5.0     6.070336
5        6.0     6.036585
6        7.0     4.527778
7        8.0     5.812308
8        9.0     5.271341
9       10.0     3.960245
10      11.0     5.452888
11      12.0     4.972308
12      13.0     3.776758
13      14.0     3.828746
14      15.0     4.969231
15      16.0     3.373860
16      17.0     4.272171
17      18.0     4.521341
18      19.0     4.592705
19      20.0     4.114198
20      21.0     3.376900
21      22.0     4.631902
22      23.0     4.376900
23      24.0     4.009119
24      25.0     5.201835
25      26.0     4.361702
26      27.0     4.571865
27      28.0     4.613982
28      29.0     4.390244
29      30.0     2.609091
30      31.0     4.288754
31      32.0     3.905199
32      33.0     3.907692
33      34.0     4.387195
34      35.0     3.710366
35      36.0     3.848024
36      37.0     2.764526
37      38.0     4.127660
38      39.0     4.871166
39      40.0     3.993921
40      41.0     5.206687
41      42.0     2.541033
42      43.0     4.097561
43      44.0     3.054545

In [24]:
output_path = r'.\output\44_noise_score_mean.csv'
noise_mean_score.to_csv(output_path, index=None)